ktor:
    application:
        modules:
            - com.example.com.ApplicationKt.module
    deployment:
        port: 8080

# Azure Services Configuration
azure:
    vision:
        # Replace these placeholder values with your actual Azure Computer Vision API keys
        key: ${1Oj4uI2OtyNZmUil8D2FI2BhB4wXeORd5btA3FdhfnFMMZ1qWNTpJQQJ99BDACmepeSXJ3w3AAAFACOGJ2Eq}
        endpoint: ${https://hearing-aid-vision.cognitiveservices.azure.com/}
